apiVersion: v1
kind: PersistentVolume
metadata:
  name: gettingstarted-pv
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 5Gi
  accessModes: 
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete  
  hostPath:
    path: "/mnt/data"
    type: DirectoryOrCreate
     
